import './globals.css'
import { Rubik } from 'next/font/google'

// COMPONENTS
import Navbar from './components/navbar'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'HelpDesk',
  description: 'Generated by create next JS',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Navbar />
        
        {children}
        
        </body>
    </html>
  )
}
